#include "game.h"

void Game::addGrass() {
    // topleft x, topleft y, width, height

    BoundingBox g1 = { STARTING_BACKGROUND_X + TREE_WIDTH*3, STARTING_BACKGROUND_Y + TREE_HEIGHT*5 + GRASS_HEIGHT*2, GRASS_WIDTH*5, GRASS_HEIGHT*15 };
    grass.push_back(g1);

    BoundingBox g2 = { STARTING_BACKGROUND_X + TREE_WIDTH*4 + GRASS_WIDTH*5, STARTING_BACKGROUND_Y + TREE_HEIGHT*6, GRASS_WIDTH*5, GRASS_HEIGHT*16 };
    grass.push_back(g2);

    BoundingBox g3 = { STARTING_BACKGROUND_X + TREE_WIDTH*5 + GRASS_WIDTH*5, STARTING_BACKGROUND_Y + TREE_HEIGHT*6, GRASS_WIDTH*5, GRASS_HEIGHT*10 };
    grass.push_back(g3);

    BoundingBox g4 = { STARTING_BACKGROUND_X + TREE_WIDTH*6 + GRASS_WIDTH*5, STARTING_BACKGROUND_Y + TREE_HEIGHT*6, GRASS_WIDTH*5, GRASS_HEIGHT*9 };
    grass.push_back(g4);

    BoundingBox g5 = { STARTING_BACKGROUND_X + TREE_WIDTH*6 + GRASS_WIDTH*10, STARTING_BACKGROUND_Y + TREE_HEIGHT*6 + GRASS_HEIGHT*3, GRASS_WIDTH*1, GRASS_HEIGHT*6 };
    grass.push_back(g5);

    BoundingBox g6 = { STARTING_BACKGROUND_X + TREE_WIDTH*6 + GRASS_WIDTH*11, STARTING_BACKGROUND_Y + TREE_HEIGHT*6 + GRASS_HEIGHT*3, GRASS_WIDTH*5, GRASS_HEIGHT*4 };
    grass.push_back(g6);

    BoundingBox g7 = { STARTING_BACKGROUND_X + TREE_WIDTH*6 + GRASS_WIDTH*8, STARTING_BACKGROUND_Y + TREE_HEIGHT*6 + GRASS_HEIGHT*9, GRASS_WIDTH*3, GRASS_HEIGHT*1 };
    grass.push_back(g7);

    BoundingBox g8 = { STARTING_BACKGROUND_X + TREE_WIDTH*6 + GRASS_WIDTH*11, STARTING_BACKGROUND_Y + TREE_HEIGHT*6 + GRASS_HEIGHT*7, GRASS_WIDTH*4, GRASS_HEIGHT*1 };
    grass.push_back(g8);

    BoundingBox g9 = { STARTING_BACKGROUND_X + TREE_WIDTH*4 + GRASS_WIDTH*10, STARTING_BACKGROUND_Y + TREE_HEIGHT*6 + GRASS_HEIGHT*14, GRASS_WIDTH*2, GRASS_HEIGHT*2 };
    grass.push_back(g9);

    BoundingBox g10 = { STARTING_BACKGROUND_X + TREE_WIDTH*15, STARTING_BACKGROUND_Y + TREE_HEIGHT*15 - GRASS_HEIGHT*1, GRASS_WIDTH*3, GRASS_HEIGHT*28 };
    grass.push_back(g10);

    BoundingBox g11 = { STARTING_BACKGROUND_X + TREE_WIDTH*15 + GRASS_WIDTH*3, STARTING_BACKGROUND_Y + TREE_HEIGHT*15 - GRASS_HEIGHT*1, GRASS_WIDTH*1, GRASS_HEIGHT*15 };
    grass.push_back(g11);

    BoundingBox g12 = { STARTING_BACKGROUND_X + TREE_WIDTH*15 + GRASS_WIDTH*4, STARTING_BACKGROUND_Y + TREE_HEIGHT*15, GRASS_WIDTH*1, GRASS_HEIGHT*13 };
    grass.push_back(g12);

    BoundingBox g13 = { STARTING_BACKGROUND_X + TREE_WIDTH*3, STARTING_BACKGROUND_Y + TREE_HEIGHT*19, GRASS_WIDTH*15, GRASS_HEIGHT*5 };
    grass.push_back(g13);

    BoundingBox g14 = { STARTING_BACKGROUND_X + TREE_WIDTH*8, STARTING_BACKGROUND_Y + TREE_HEIGHT*21, GRASS_WIDTH*15, GRASS_HEIGHT*1 };
    grass.push_back(g14);

    BoundingBox g15 = { STARTING_BACKGROUND_X + TREE_WIDTH*6, STARTING_BACKGROUND_Y + TREE_HEIGHT*21 + GRASS_HEIGHT*1, GRASS_WIDTH*16, GRASS_HEIGHT*2 };
    grass.push_back(g15);

    BoundingBox g16 = { STARTING_BACKGROUND_X + TREE_WIDTH*6 + GRASS_WIDTH*19, STARTING_BACKGROUND_Y + TREE_HEIGHT*21 + GRASS_HEIGHT*1, GRASS_WIDTH*2, GRASS_HEIGHT*13 };
    grass.push_back(g16);

    BoundingBox g17 = { STARTING_BACKGROUND_X + TREE_WIDTH*6 + GRASS_WIDTH*2, STARTING_BACKGROUND_Y + TREE_HEIGHT*21 + GRASS_HEIGHT*2, GRASS_WIDTH*3, GRASS_HEIGHT*11 };
    grass.push_back(g17);

    BoundingBox g18 = { STARTING_BACKGROUND_X + TREE_WIDTH*9 + GRASS_WIDTH*5, STARTING_BACKGROUND_Y + TREE_HEIGHT*23, GRASS_WIDTH*2, GRASS_HEIGHT*11 };
    grass.push_back(g18);

    BoundingBox g19 = { STARTING_BACKGROUND_X + TREE_WIDTH*3, STARTING_BACKGROUND_Y + TREE_HEIGHT*27, GRASS_WIDTH*9, GRASS_HEIGHT*4 };
    grass.push_back(g19);

    BoundingBox g20 = { STARTING_BACKGROUND_X + TREE_WIDTH*6 + GRASS_WIDTH*5, STARTING_BACKGROUND_Y + TREE_HEIGHT*27, GRASS_WIDTH*9, GRASS_HEIGHT*2 };
    grass.push_back(g20);

    BoundingBox g21 = { STARTING_BACKGROUND_X + TREE_WIDTH*7 + GRASS_WIDTH*18, STARTING_BACKGROUND_Y + TREE_HEIGHT*27, GRASS_WIDTH*6, GRASS_HEIGHT*2 };
    grass.push_back(g21);

    BoundingBox g22 = { STARTING_BACKGROUND_X + MAP_WIDTH - TREE_WIDTH*5, STARTING_BACKGROUND_Y + TREE_HEIGHT*27, GRASS_WIDTH*6, GRASS_HEIGHT*2 };
    grass.push_back(g22);

    BoundingBox g23 = { STARTING_BACKGROUND_X + TREE_WIDTH*6 + GRASS_WIDTH*3, STARTING_BACKGROUND_Y + TREE_HEIGHT*27 + GRASS_HEIGHT*2, GRASS_WIDTH*12, GRASS_HEIGHT*1 };
    grass.push_back(g23);

    BoundingBox g24 = { STARTING_BACKGROUND_X + TREE_WIDTH*7 + GRASS_WIDTH*17, STARTING_BACKGROUND_Y + TREE_HEIGHT*27 + GRASS_HEIGHT*2, GRASS_WIDTH*9, GRASS_HEIGHT*1 };
    grass.push_back(g24);

    BoundingBox g25 = { STARTING_BACKGROUND_X + MAP_WIDTH - TREE_WIDTH*5 - GRASS_WIDTH*1, STARTING_BACKGROUND_Y + TREE_HEIGHT*27 + GRASS_HEIGHT*2, GRASS_WIDTH*7, GRASS_HEIGHT*3 };
    grass.push_back(g25);

    BoundingBox g26 = { STARTING_BACKGROUND_X + TREE_WIDTH*6 + GRASS_WIDTH*4, STARTING_BACKGROUND_Y + TREE_HEIGHT*27 + GRASS_HEIGHT*3, GRASS_WIDTH*10, GRASS_HEIGHT*1 };
    grass.push_back(g26);

    BoundingBox g27 = { STARTING_BACKGROUND_X + TREE_WIDTH*7 + GRASS_WIDTH*18, STARTING_BACKGROUND_Y + TREE_HEIGHT*27 + GRASS_HEIGHT*3, GRASS_WIDTH*7, GRASS_HEIGHT*1 };
    grass.push_back(g27);

    BoundingBox g28 = { STARTING_BACKGROUND_X + TREE_WIDTH*3, STARTING_BACKGROUND_Y + TREE_HEIGHT*27 + GRASS_HEIGHT*4, GRASS_WIDTH*8, GRASS_HEIGHT*3 };
    grass.push_back(g28);

    BoundingBox g29 = { STARTING_BACKGROUND_X + MAP_WIDTH - TREE_WIDTH*5 - GRASS_WIDTH*2, STARTING_BACKGROUND_Y + TREE_HEIGHT*27 + GRASS_HEIGHT*5, GRASS_WIDTH*8, GRASS_HEIGHT*2 };
    grass.push_back(g29);
}